def display_menu():
    print("\nBadget tracker CLI")
    print("1. Create User")
    print("2. Delete User")
    print("3. Display Users")
    print("4. Find User by Attribute")
    print("5. Create Category")
    print("6. Delete Category")
    print("7. Display Categories")
    print("8. Create Transaction")
    print("9. Delete Transaction")
    print("10. Display Transactions")
    print("11. View User Transactions")
    print("q. Quit")