def display_menu():
    print("\nBadget tracker CLI")
    print("1. Create User")
    print("2. Delete User")
    print("3. Display Users")
    print("4. Find User by Attribute")
    print("5. Create Category")
    print("6. Delete Category")
    print("7. Find Category by ID")
    print("8. Display Categories")
    print("9. Create Transaction")
    print("10. Delete Transaction")
    print("11. Display Transactions")
    print("12. Find Transaction by ID")
    print("13. View User Transactions")
    print("q. Quit")