"""Add user_id to Category model

Revision ID: 1b84156380ae
Revises: 366dcd4f2ffb
Create Date: 2024-09-18 14:22:53.978298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b84156380ae'
down_revision: Union[str, None] = '366dcd4f2ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_categories_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories') as batch_op:
        batch_op.drop_constraint('fk_categories_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###